version: "3.7"

services:
        service1:
           build:
             context: /home/student/Mentoredproject/service-1/
             dockerfile: dockerfile
           ports:
           - target: 5000
           published: 5000
           protocol: tcp
        service2:
           build:
             context: /home/student/Mentoredproject/service-2/
             dockerfile: dockerfile
           ports:
           - target: 5001
           published: 5001
           protocol: tcp
        service3:
           build:
             context: /home/student/Mentoredproject/service-3/
             dockerfile: dockerfile
           ports:
           - target: 5002
           published: 5002
           protocol: tcp
        service4:
           build:     
            context: /home/student/Mentoredproject/service-4/
            dockerfile: dockerfile
           ports:
           - target: 5003
           published: 5003
           protocol: tcp
          
